//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// CalcCkeck.rc에서 사용되고 있습니다.
//
#define IDS_ABOUTBOX                    101
#define IDS_STRING102                   102
#define IDS_STRING103                   103
#define IDS_STRING104                   104
#define IDS_STRING105                   105
#define IDS_STRING106                   106
#define IDS_STRING107                   107
#define IDS_STRING108                   108
#define IDS_STRING109                   109
#define IDS_STRING110                   110
#define IDS_STRING111                   111
#define IDS_STRING112                   112
#define IDS_STRING113                   113
#define IDS_STRING114                   114
#define IDS_STRING115                   115
#define IDS_STRING116                   116
#define IDS_STRING117                   117
#define IDS_STRING118                   118
#define IDS_STRING119                   119
#define IDS_STRING120                   120
#define IDS_STRING121                   121
#define IDS_STRING122                   122
#define IDS_STRING123                   123
#define IDS_STRING124                   124
#define IDS_STRING125                   125
#define IDS_STRING126                   126
#define IDS_STRING127                   127
#define IDR_MAINFRAME                   128
#define IDS_STRING128                   128
#define IDS_STRING129                   129
#define IDR_MENU                        130
#define IDS_NOZZLE1                     130
#define IDS_NOZZLE2                     131
#define IDD_Dialog_Help                 132
#define IDS_CLIP                        132
#define IDD_Dialog_Option               133
#define IDS_FNS_NOZZLE                  133
#define IDD_Dialog_Image                134
#define IDS_FNS_CLIP                    134
#define IDS_DIR_NOZZLE                  135
#define IDB_PNG_NOZZLE                  136
#define IDS_DIR_CLIP                    136
#define IDB_PNG_CLIP1                   137
#define IDB_PNG_CLIP2                   138
#define IDD_Dialog_SecureWarning        139
#define IDR_IMG_NZ1                     139
#define IDB_Bitmap_Base                 140
#define IDR_IMG_NZ2                     140
#define IDB_Bitmap_PLATE                141
#define IDR_IMG_NZ3                     141
#define IDB_Bitmap_Base2                142
#define IDR_IMG_NZ4                     142
#define IDB_Bitmap_Base3                143
#define IDR_IMG_CLP1                    143
#define IDB_Bitmap_Base4                144
#define IDR_IMG_CLP2                    144
#define IDB_Bitmap_Base5                145
#define IDR_IMG_CLP3                    145
#define IDB_Bitmap_Base6                146
#define IDR_IMG_CLP4                    146
#define IDB_Bitmap_Base7                147
#define IDR_IMG_CLP5                    147
#define IDB_Bitmap_Base8                148
#define IDR_RCDATA1                     148
#define IDD_Main_Dialog                 149
#define IDB_Bitmap_Base9                149
#define IDR_RCDATA3                     150
#define IDB_Bitmap_SHELL                151
#define IDD_Nozzle_Length_Ckeck         152
#define IDB_Bitmap_Base12               152
#define IDB_Bitmap_RoundBar             152
#define IDD_Clip_Length_Ckeck           153
#define IDS_IMG_NZ1                     198
#define IDS_IMG_NZ2                     199
#define IDS_IMG_NZ3                     200
#define IDS_IMG_NZ4                     201
#define IDS_IMG_CLP1                    202
#define IDS_IMG_CLP2                    203
#define IDS_IMG_CLP3                    204
#define IDS_IMG_CLP4                    205
#define IDS_IMG_CLP5                    206
#define IDC_Radio_Shell                 1000
#define IDC_Button_Reset                1000
#define IDC_Radio_AppOval               1001
#define IDC_Edit_Shell_OD               1001
#define IDC_Radio_RghtOval              1002
#define IDC_Edit_Shell_OR               1002
#define IDC_Edit_Dbl_Width              1003
#define IDC_Edit_Shell_ID               1004
#define IDC_Edit_Pad_THK                1004
#define IDC_Check_Ves_CL_0              1005
#define IDC_Edit_Clip_THK               1005
#define IDC_Edit_Shell_THK              1006
#define IDC_Edit_Clip_Proj              1006
#define IDC_Edit_Shell_Rad              1007
#define IDC_Edit_Clip_LTD               1007
#define IDC_Edit_Head_THK               1008
#define IDC_Static_CL1                  1008
#define IDC_Combo_digit                 1009
#define IDC_Combo_Pipe_Size             1009
#define IDC_Edit_Width                  1009
#define IDC_Button_DirSelect            1010
#define IDC_Button_CCalc                1010
#define IDC_Edit_x_Dstnce               1011
#define IDC_Static_CL2                  1011
#define IDC_Edit_Y_Dstnce               1012
#define IDC_Edit_Ves_CL_TO              1013
#define IDC_Edit_Noz_Proj               1014
#define IDC_Edit_Clip_Length            1014
#define IDC_Edit_Noz_Size               1015
#define IDC_STATIC2                     1017
#define IDC_STATIC3                     1018
#define IDC_Static_Image                1018
#define IDC_STATIC4                     1019
#define IDC_COMBO1                      1019
#define IDC_Combo_Img                   1019
#define IDC_STATIC5                     1020
#define IDC_Static_NL1                  1020
#define IDC_Button_SetImage             1020
#define IDC_Static_NL3                  1021
#define IDC_Static_L3                   1021
#define IDC_Static_NL2                  1022
#define IDC_Static_NL4                  1023
#define IDC_L1_Rr                       1024
#define IDC_Static_Clp_Stat             1024
#define IDC_L2_Rr                       1025
#define IDC_Edit_Password               1026
#define IDC_Edit_Length_B               1028
#define IDC_Static_CurFileDir           1029
#define IDC_Tab_Main                    1030
#define ID_Menu_Option                  32782
#define ID_Menu_FileSave                32783
#define ID_Menu_FileLoad                32784
#define ID_Menu_Help                    32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1021
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
